services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000/api
        NEXT_PUBLIC_SOCKET_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge
